// src/components/theme-selector/theme-grid.vue
<script setup lang="ts">
import { useTranslation } from 'i18next-vue'

import { ThemeNodeModel } from '@/services/themes/themes.model'

const { t } = useTranslation()
const props = defineProps<{
  themes: ThemeNodeModel[]
}>()
</script>

<template>
  <div class="flex flex-row flex-wrap pl-2.5">
    <button
      class="relative shrink-0 h-[150px] w-1/2 px-2.5 text-start text-gray-100/40 uppercase hover:bg-[#ccc]"
      v-for="theme in props.themes"
      :key="theme.id"
      :class="`bg-${theme.name}-primary hover:text-${theme.name}-primary`"
      @click="$emit('setTheme', theme.name)"
    >
      <div class="text-2xl absolute top-5">{{ t(`${theme.name}`) }}</div>
      <div
        class="text-6xl absolute bottom-1 after:font-icons"
        :class="`after:content-${theme.name}`"
      ></div>
    </button>
  </div>
</template>

// src/components/layers-panel/catalog/theme/theme-grid.component.ts
import { html, LitElement } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { ThemeNodeModel } from '../../../../services/themes/themes.model'
import i18next from 'i18next'
import { i18nMixin } from '../../../../mixins/i18n-lit-element'

@customElement('lux-theme-grid')
export class ThemeGrid extends i18nMixin(LitElement) {
  @property({ type: Object }) themes?: ThemeNodeModel[]

  render() {
    return html`${this.themes?.map(
      theme =>
        html`<button
          class="relative shrink-0 h-[150] w-1/2 px-2.5 text-start text-gray-100/40 uppercase bg-${theme.name}-primary hover:bg-[#ccc]"
          @click="${() => this.setTheme(theme.name)}"
        >
          <div class="text-2xl absolute top-5">
            ${i18next.t(`${theme.name}`)}
          </div>
          <div
            class="text-6xl absolute bottom-1 after:content-${theme.name} after:font-icons"
          ></div>
        </button>`
    )} `
  }

  setTheme(themeName: string) {
    const event = new CustomEvent(`set-theme`, {
      bubbles: true,
      detail: themeName,
    })
    this.dispatchEvent(event)
  }

  override createRenderRoot() {
    return this
  }
}
