// src/components/layers-panel/catalog/layer-metadata/layer-metadata.component.ts
import i18next from 'i18next'
import { html, LitElement, TemplateResult } from 'lit'
import { customElement, property } from 'lit/decorators'
import { i18nMixin } from '../../../../mixins/i18n-lit-element'
import { LayerMetadataModel } from './layer-metadata.model'
import './layer-metadata-item.component'
@customElement('lux-layer-metadata')
export class LayerMetadata extends i18nMixin(LitElement) {
  @property({ type: Object }) private layerMetadata?: LayerMetadataModel

  render(): TemplateResult {
    const content = this.layerMetadata
      ? html`
          <div
            class="fixed right-8 top-96 z-[100] bg-white lux-modal w-[600px] p-3"
            role="dialog"
          >
            <div class="lux-modal-header flex flex-row justify-between">
              <h1>${i18next.t(`${this.layerMetadata.title}`)}</h1>
              <button @click="${this.closeMetadata}">X</button>
            </div>
            <div class="pt-3">
              <dl>
                <lux-layer-metadata-item
                  label=${i18next.t('Name')}
                  value=${this.layerMetadata.name}
                ></lux-layer-metadata-item>
                <lux-layer-metadata-item
                  label=${i18next.t('Description du Service')}
                  value=${this.layerMetadata.serviceDescription}
                ></lux-layer-metadata-item>
                <!--short_trusted_description || trusted_description-->
                <lux-layer-metadata-item
                  label=${i18next.t('Description')}
                  value=${this.layerMetadata.description}
                ></lux-layer-metadata-item>
                <lux-layer-metadata-item
                  label=${i18next.t("Contrainte d'utilisation")}
                  value=${this.layerMetadata.legalConstraints}
                ></lux-layer-metadata-item>
                <lux-layer-metadata-item
                  label=${i18next.t('Url vers la resource')}
                  value=${this.layerMetadata.link?.join(',')}
                ></lux-layer-metadata-item>
                <lux-layer-metadata-item
                  label=${i18next.t('Revision date')}
                  value=${this.layerMetadata.revisionDate}
                ></lux-layer-metadata-item>
                <lux-layer-metadata-item
                  label=${i18next.t('Keywords')}
                  value=${this.layerMetadata.keyword?.join(',')}
                ></lux-layer-metadata-item>
                <lux-layer-metadata-item
                  label=${i18next.t('Contact')}
                  value=${this.layerMetadata.responsibleParty?.join(',')}
                ></lux-layer-metadata-item>
                <!--{{content.geonetworkBaseUrl}}/fre/catalog.search#/metadata/{{content.uid}}-->
                <lux-layer-metadata-item
                  label=${i18next.t('Link to the metadata')}
                  value=${this.layerMetadata.metadataLink}
                ></lux-layer-metadata-item>
                <lux-layer-metadata-item
                  label=${i18next.t('The metadata is right now not available')}
                  value=${this.layerMetadata.isError}
                ></lux-layer-metadata-item>
                <lux-layer-metadata-item
                  label=${i18next.t('Legend')}
                  value=${this.layerMetadata.legendHtml}
                ></lux-layer-metadata-item>
                <!--hasLegend-->
              </dl>
            </div>
          </div>
        `
      : html``
    return content
  }

  closeMetadata() {
    const event = new CustomEvent(`close-layer-metadata`)
    this.dispatchEvent(event)
  }

  override createRenderRoot() {
    return this
  }
}

// src/components/layer-metadata/layer-metadata.vue
<script setup lang="ts">
import useFormatting from '@/composables/common/formatting.composable'
import { LayerMetadataModel } from '@/composables/layer-metadata/layer-metadata.model'
import { useTranslation } from 'i18next-vue'
import LayerMetadataItem from './layer-metadata-item.vue'

const { t } = useTranslation()
const format = useFormatting()

defineProps<{
  layerMetadata: LayerMetadataModel
}>()
const emit = defineEmits<{
  (e: 'closeLayerMetadata'): void
}>()
function closeLayerMetadata() {
  emit('closeLayerMetadata')
}
</script>

<template>
  <div
    class="fixed right-32 top-32 z-[100] bg-white lux-modal w-[600px] p-3"
    role="dialog"
  >
    <div class="lux-modal-header flex flex-row justify-between">
      <h1>{{ t(`${layerMetadata.title}`) }}</h1>
      <button @click="closeLayerMetadata">X</button>
    </div>
    <div class="grid gap-2 grid-cols-3 pt-3 text-[13px] font-arial">
      <layer-metadata-item
        v-if="layerMetadata.name"
        :label="t('Name')"
        :value="layerMetadata.name"
      ></layer-metadata-item>
      <layer-metadata-item
        v-if="layerMetadata.serviceDescription"
        :label="t('Description du Service')"
        :value="layerMetadata.serviceDescription"
      ></layer-metadata-item>
      <div
        v-if="layerMetadata.description"
        class="col-span-3 grid gap-2 grid-cols-3"
      >
        <span class="font-bold">{{ t('Description') }}</span>
        <span
          v-dompurify-html="layerMetadata.description"
          class="col-span-2"
        ></span>
      </div>
      <layer-metadata-item
        v-if="layerMetadata.legalConstraints"
        :label="t(`Contrainte d'utilisation`)"
        :value="layerMetadata.legalConstraints"
      ></layer-metadata-item>
      <div class="col-span-3" v-if="layerMetadata.link?.length !== 0">
        <div
          class="grid gap-2 grid-cols-3"
          v-for="link in layerMetadata.link"
          :key="link"
        >
          <span class="font-bold">{{ t('Url vers la resource') }}</span>
          <span class="col-span-2">
            <a
              class="text-secondary hover:underline"
              target="_blank"
              :href="link"
              >{{ link }}</a
            >
          </span>
        </div>
      </div>
      <layer-metadata-item
        v-if="layerMetadata.revisionDate"
        :label="t('Revision date')"
        :value="format.formatDate(layerMetadata.revisionDate)"
      ></layer-metadata-item>
      <layer-metadata-item
        v-if="layerMetadata.keyword"
        :label="t('Keywords')"
        :value="layerMetadata.keyword?.join(',')"
      ></layer-metadata-item>
      <div
        class="col-span-3 grid gap-2 grid-cols-3"
        v-if="layerMetadata.responsibleParty"
      >
        <span class="font-bold">{{ t('Contact') }}</span>
        <span class="col-span-2">
          <p v-if="layerMetadata.responsibleParty?.organisaton">
            {{ layerMetadata.responsibleParty?.organisaton }}
          </p>
          <p v-if="layerMetadata.responsibleParty?.name">
            {{ layerMetadata.responsibleParty?.name }}
          </p>
          <p v-if="layerMetadata.responsibleParty?.unknown">
            {{ layerMetadata.responsibleParty?.unknown }}
          </p>
          <p v-if="layerMetadata.responsibleParty?.address">
            {{ layerMetadata.responsibleParty?.address }}
          </p>
          <p v-if="layerMetadata.responsibleParty?.email">
            <a
              class="text-secondary hover:underline"
              :href="'mailto:' + layerMetadata.responsibleParty?.email"
              >{{ layerMetadata.responsibleParty?.email }}</a
            >
          </p>
        </span>
      </div>
      <div
        class="grid gap-2 grid-cols-3 col-span-3"
        v-if="layerMetadata.metadataLink"
      >
        <span class="font-bold">{{ t('Link to the metadata') }}</span>
        <span class="col-span-2">
          <a
            class="text-secondary hover:underline"
            target="_blank"
            :href="layerMetadata.metadataLink"
            >{{ t('link') }}</a
          >
        </span>
      </div>
      <layer-metadata-item
        v-if="layerMetadata.isError"
        :label="t('The metadata is right now not available')"
        :value="t(`${layerMetadata.isError}`)"
      ></layer-metadata-item>
      <div v-if="layerMetadata.legendHtml">
        <h4>{{ t('Legend') }}</h4>
        <span v-dompurify-html="layerMetadata.legendHtml?.innerHTML"></span>
      </div>
      <!--hasLegend-->
    </div>
  </div>
</template>
